swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: API documentation for managing user transactions
  version: "2.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Retrieve all transactions grouped by account for the current month
      description: Fetch all transactions for the current month grouped by account. You can filter by month if needed.
      parameters:
        - in: query
          name: month
          type: string
          required: false
          description: The month for which to retrieve transactions (format YYYY-MM). Defaults to the current month if not provided.
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieved transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionGroup"
        "400":
          description: Invalid query parameter
        "401":
          description: Unauthorized access
        "500":
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Retrieve detailed information for a specific transaction
      description: Get detailed information about a single transaction, including its amount, date, category, notes, and transaction type.
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: The ID of the transaction to retrieve
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieved transaction details
          schema:
            $ref: "#/definitions/TransactionDetails"
        "400":
          description: Invalid transaction ID
        "401":
          description: Unauthorized access
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update category or notes for a specific transaction
      description: Modify the `category` or `notes` of an existing transaction. The `transactionType` cannot be modified.
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: The ID of the transaction to update
        - in: body
          name: body
          description: Updated transaction details
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Successfully updated transaction
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid input data
        "401":
          description: Unauthorized access
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

definitions:
  TransactionGroup:
    type: object
    properties:
      accountId:
        type: string
        description: The ID of the account
      transactions:
        type: array
        description: List of transactions for the account
        items:
          $ref: "#/definitions/Transaction"

  Transaction:
    type: object
    required:
      - id
      - accountId
      - date
      - amount
      - description
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      accountId:
        type: string
        description: The ID of the account associated with the transaction
      date:
        type: string
        format: date
        description: The date when the transaction occurred
      amount:
        type: number
        format: float
        description: The amount of the transaction
      description:
        type: string
        description: A brief description of the transaction

  TransactionDetails:
    type: object
    required:
      - id
      - accountId
      - date
      - amount
      - transactionType
      - description
      - category
      - notes
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      accountId:
        type: string
        description: The ID of the account associated with the transaction
      date:
        type: string
        format: date
        description: The date when the transaction occurred
      amount:
        type: number
        format: float
        description: The amount of the transaction
      description:
        type: string
        description: A brief description of the transaction
      transactionType:
        type: string
        description: The type of the transaction (e.g., "Debit", "Credit")
      category:
        type: string
        description: The category of the transaction (e.g., "Food", "Transport")
      notes:
        type: string
        description: Additional notes related to the transaction

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: The category of the transaction
      notes:
        type: string
        description: Additional notes related to the transaction

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
